<?php

/** @var $viewModel \Yohanes\Vendor\ViewModel\VendorViewModel */
$viewModel = $block->getViewModel();

?>

<?php if ($viewModel->getVendor()): ?>
<div class="vendor-container">
    <div class="top">
        <div class="image">
            <img src="<?= $viewModel->getImageUrl()?>"  alt="<?= $viewModel->getName()?> Logo"/>
        </div>
        <div class="name">
            <h2 class="name"><?= $viewModel->getName()?></h2>
        </div>
    </div>
    <div class="bottom">
        <div class="description"><?= $viewModel->getDescription()?></div>
    </div>

</div>
<?php endif; ?>
